[build]
  base = "frontend"
  command = "pnpm build"
  publish = "frontend/.next"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "9"

# Ignore backend files
[build.ignore]
  ignore = "backend/*"

[[redirects]]
  from = "/dashboard"
  to = "/dashboard/portfolio"
  status = 302

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
