[build]
  base = "frontend"
  command = "pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.19.0"
  PNPM_VERSION = "9"

[[redirects]]
  from = "/dashboard"
  to = "/dashboard/portfolio"
  status = 302

# Handle Next.js client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"