version: '3.8'

services:
  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Satoshi Sensei Backend
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./satoshi_sensei.db
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=development
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - ./data:/app/data  # For SQLite database persistence
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  redis_data:
